server:
  port: 8090
  address: 0.0.0.0

# database configuration
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://172.21.0.2:5432/tms_db
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 200MB

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

# logging
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug

# jwt property
jwt:
  secret-key: X7BSnMS4e12M0Sz/4IWr+VPNK6vpAee5LfhaM3scjiU=
  token-expiration-in-minutes: 1
