server:
  port: 8090
  address: 0.0.0.0

# database configuration
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/tms_db
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 200MB

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true

# logging
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    com.tms.easyrento.dbMappers: debug

# jwt property
jwt:
  secret-key: X7BSnMS4e12M0Sz/4IWr+VPNK6vpAee5LfhaM3scjiU=
  token-expiration-in-minutes: 1

# identify mybatis mapper
mybatis:
  mapper-locations: classpath*:**/mappers/*Mapper.xml
  type-aliases-package: classpath*:**/java/com/tms/easyrento/dto/**

# FLYWAY