### REGISTER NEW USER
POST http://localhost:8090/api/v1/user-accounts
Content-Type: application/json

{
  "email": "abhi@yopmail.com",
  "username": "abhi-kafle",
  "password": "Test@123"
}

### GET ALL REGISTERED USERS
GET http://localhost:8090/api/v1/user-accounts?isActive=-2

### GET LOGGED IN USER DETAILS
GET http://localhost:8090/api/v1/user-accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnVuQHlvcG1haWwuY29tIiwidXNlcklkIjoxLCJpYXQiOjE3MDY1MjgwNjUsImV4cCI6MTcwNzM5MjA2NX0.-tScDoAzFlwpaYv8INBDjLHEAONeQHeUmHqCcAzVv4o

{
  "userId": 1,
  "authToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnVuQHlvcG1haWwuY29tIiwidXNlcklkIjoxLCJpYXQiOjE3MDY1MjgwNjUsImV4cCI6MTcwNzM5MjA2NX0.-tScDoAzFlwpaYv8INBDjLHEAONeQHeUmHqCcAzVv4o"
}

### all property
GET http://localhost:8090/api/v1/properties/get-info/all
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsInN1YiI6ImFydW5AeW9wbWFpbC5jb20iLCJpYXQiOjE3MDY1NTQwNjUsImV4cCI6MTcwNzQxODA2NX0.6mf8vox4rDxFevhBl0D5Q4UYF_Q-zjFbdFfU6AR3M0E

### GET OFFERS FOR TENANTS
GET http://localhost:8090/api/v1/owners/get-offers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnVuQHlvcG1haWwuY29tIiwidXNlcklkIjoxLCJpYXQiOjE3MDY1MjgwNjUsImV4cCI6MTcwNzM5MjA2NX0.-tScDoAzFlwpaYv8INBDjLHEAONeQHeUmHqCcAzVv4o

### GET PROPERTY IMAGE
GET http://localhost:8090/api/v1/properties/get/7b2763f0-3187-455e-96cb-05baed705f70

### GET OFFERS COUNT FOR OWNER
GET http://localhost:8090/api/v1/owners/get-offers-count/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsInN1YiI6ImFydW5AeW9wbWFpbC5jb20iLCJpYXQiOjE3MDY1NTQwNjUsImV4cCI6MTcwNzQxODA2NX0.6mf8vox4rDxFevhBl0D5Q4UYF_Q-zjFbdFfU6AR3M0E

### SOFT DELETE USER
DELETE http://localhost:8090/api/v1/user-accounts/1

### CORS CONFIGURATION
OPTIONS http://localhost:8090/api/v1/user-accounts/1
Origin: http://127.0.0.1:5173


//Saving a variable
> {%
    client.global.set("bearer_token", response.body.json.token);
%}
### PRODUCT
POST http://localhost:8090/api/v1/properties
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnVuQHlvcG1haS5jb20iLCJpYXQiOjE3MDU1ODc4NzUsImV4cCI6MTcwNjQ1MTg3NX0.zc_Of0yJO7YK051919tetgvdRXMrE-ZEYZlsip0qCuI

{
  "id": null,
  "propertyCode": "property-code12",
  "propertyType": "ROOM",
  "allocatedPrice": 0,
  "pricePerUnit": 0,
  "totalRooms": 0,
  "ownerId": 1,
  "wardNo": 0,
  "addressType": "addressType_946be35e4a37",
  "streetName": "streetName_66056495d8e6",
  "streetNameNp": "streetNameNp_0765c4dd56d2",
  "googleLocation": "googleLocation_bf47c530489a"
}

###
POST http://localhost:8090/api/v1/properties
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnVuQHlvcG1haS5jb20iLCJpYXQiOjE3MDU1ODc4NzUsImV4cCI6MTcwNjQ1MTg3NX0.zc_Of0yJO7YK051919tetgvdRXMrE-ZEYZlsip0qCuI

{
  "id": null,
  "title": "4 bhk flat here",
  "propertyType": "LAND",
  "allocatedPrice": 5000,
  "pricePerUnit": 5003,
  "totalRooms": null,
  "occupied": "",
  "imageFiles": [
    {
      "id": 0,
      "name": "jwt-authentication-spring-TenantManagementSystem(1).png",
      "thumbnail": "blob:http://localhost:5173/23044a91-583e-42f3-b5d5-5b211a75e067",
      "file": {}
    },
    {
      "id": 1,
      "name": "jwt-authentication-spring-TenantManagementSystem(2).png",
      "thumbnail": "blob:http://localhost:5173/c62f35eb-b2f4-40fb-bf2d-6cf9ad88babf",
      "file": {}
    },
    {
      "id": 2,
      "name": "373406301_6687371731323555_7453406639323591144_n.jpg",
      "thumbnail": "blob:http://localhost:5173/b03c6935-5289-4d50-a45d-70d63ed57449",
      "file": {}
    },
    {
      "id": 3,
      "name": "Blank diagram.png",
      "thumbnail": "blob:http://localhost:5173/d0350f14-8da4-455a-b8e8-ee4951c43a0a",
      "file": {}
    }
  ],
  "roomNumberInfo": {
    "totalBathRooms": 3,
    "totalBedRooms": 2,
    "totalLivingRooms": 2,
    "totalExternalBathRooms": 2
  },
  "ownerId": 1,
  "propertyAddress": {
    "addressType": "P",
    "wardNo": "2",
    "googleLocation": null,
    "streetName": "street name",
    "streetNameNp": null
  },
  "description": "drssrsrsrs gfgf huhuh"
}

### Property Request from browser


#{"id":"","title":"one house","propertyType":"APARTMENT","allocatedPrice":"7000","pricePerUnit":"70000","occupied":"true","totalRooms":"0","addressType":"P","wardNo":"7","streetName":"new street name","streetNameNp":"null","googleLocation":"null","totalBathRooms":"7","totalBedRooms":"null","totalLivingRooms":"5","totalExternalBathRooms":"null","imageFiles":"[object Object],[object Object]","ownerId":"1","description":"this is a good property that you guys want for yourself.","multipartFiles":[{},{}]}


### Property meta info
GET http://localhost:8090/api/v1/properties/get-info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnVuQHlvcG1haS5jb20iLCJpYXQiOjE3MDU1ODc4NzUsImV4cCI6MTcwNjQ1MTg3NX0.zc_Of0yJO7YK051919tetgvdRXMrE-ZEYZlsip0qCuI



### CREATE NEW OWNER
POST http://localhost:8090/api/v1/owners
Content-Type: application/json

{
  "id": null,
  "name": "abhi",
  "nameNp": "abhi_np"
}

### GET ALL PRODUCTS
GET http://localhost:8090/api/v1/properties?isActive=1

### CHECK ENTITY GRAPH
GET http://localhost:8090/api/v1/properties/1


### REGISTER NEW TENANT
POST http://localhost:8090/api/v1/tenants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnVuQHlvcG1haS5jb20iLCJpYXQiOjE3MDU1ODc4NzUsImV4cCI6MTcwNjQ1MTg3NX0.zc_Of0yJO7YK051919tetgvdRXMrE-ZEYZlsip0qCuI

{
  "id": 0,
  "gender": "MALE",
  "name": "name_47437d38dcb1",
  "nameNp": "nameNp_9eb43b437fd5",
  "netWorth": 5000,
  "occupation": "occupation_5bc61ffe41a0",
  "phoneNo": "9812908027",
  "email": "email@gmail.com",
  "address": {
    "id": null,
    "wardNo": 4,
    "addressType": "T",
    "streetName": "Jorpati",
    "streetNameNp": "Jorpati-nepali",
    "googleLocation": "location-google"
  }
}
